<?php
/**
 * Capability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Capability Class Doc Comment
 *
 * @category    Class
 * @description The capability of the machine to play different kind of features.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Capability implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Capability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'resource' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'resource' => 'resource'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'resource' => 'setResource'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'resource' => 'getResource'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const RESOURCE_AURORA = 'AURORA';
    const RESOURCE_S6 = 'S6';
    const RESOURCE_BROWSER = 'BROWSER';
    const RESOURCE_OCV_D6 = 'OCV_D6';
    const RESOURCE_OCV_H6 = 'OCV_H6';
    const RESOURCE_OCV_FG = 'OCV_FG';
    const RESOURCE_OCV_SP = 'OCV_SP';
    const RESOURCE_OCV_MT = 'OCV_MT';
    const RESOURCE_OCV_KT = 'OCV_KT';
    const RESOURCE_OCV_GG = 'OCV_GG';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getResourceAllowableValues()
    {
        return [
            self::RESOURCE_AURORA,
            self::RESOURCE_S6,
            self::RESOURCE_BROWSER,
            self::RESOURCE_OCV_D6,
            self::RESOURCE_OCV_H6,
            self::RESOURCE_OCV_FG,
            self::RESOURCE_OCV_SP,
            self::RESOURCE_OCV_MT,
            self::RESOURCE_OCV_KT,
            self::RESOURCE_OCV_GG,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['resource'] = isset($data['resource']) ? $data['resource'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = ["AURORA", "S6", "BROWSER", "OCV_D6", "OCV_H6", "OCV_FG", "OCV_SP", "OCV_MT", "OCV_KT", "OCV_GG"];
        if (!in_array($this->container['resource'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'resource', must be one of 'AURORA', 'S6', 'BROWSER', 'OCV_D6', 'OCV_H6', 'OCV_FG', 'OCV_SP', 'OCV_MT', 'OCV_KT', 'OCV_GG'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = ["AURORA", "S6", "BROWSER", "OCV_D6", "OCV_H6", "OCV_FG", "OCV_SP", "OCV_MT", "OCV_KT", "OCV_GG"];
        if (!in_array($this->container['resource'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets resource
     * @return string
     */
    public function getResource()
    {
        return $this->container['resource'];
    }

    /**
     * Sets resource
     * @param string $resource The kind of player to select.
     * @return $this
     */
    public function setResource($resource)
    {
        $allowed_values = array('AURORA', 'S6', 'BROWSER', 'OCV_D6', 'OCV_H6', 'OCV_FG', 'OCV_SP', 'OCV_MT', 'OCV_KT', 'OCV_GG');
        if (!is_null($resource) && (!in_array($resource, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'resource', must be one of 'AURORA', 'S6', 'BROWSER', 'OCV_D6', 'OCV_H6', 'OCV_FG', 'OCV_SP', 'OCV_MT', 'OCV_KT', 'OCV_GG'");
        }
        $this->container['resource'] = $resource;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


