<?php
/**
 * Entity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Entity Class Doc Comment
 *
 * @category    Class
 * @description Hold identification and ownership of loged entites.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Entity implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Entity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'entity_type' => '\Swagger\Client\Model\EntityType_[]',
        'id' => 'int',
        'name' => 'string',
        'last_name' => 'string',
        'ext_id' => 'string',
        'ext_data' => 'object',
        'parent_id' => 'int',
        'enabled' => 'bool',
        'test_mode' => 'bool',
        'hardware_id' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'entity_type' => 'entityType',
        'id' => 'id',
        'name' => 'name',
        'last_name' => 'lastName',
        'ext_id' => 'extId',
        'ext_data' => 'extData',
        'parent_id' => 'parentId',
        'enabled' => 'enabled',
        'test_mode' => 'testMode',
        'hardware_id' => 'hardwareId'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'entity_type' => 'setEntityType',
        'id' => 'setId',
        'name' => 'setName',
        'last_name' => 'setLastName',
        'ext_id' => 'setExtId',
        'ext_data' => 'setExtData',
        'parent_id' => 'setParentId',
        'enabled' => 'setEnabled',
        'test_mode' => 'setTestMode',
        'hardware_id' => 'setHardwareId'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'entity_type' => 'getEntityType',
        'id' => 'getId',
        'name' => 'getName',
        'last_name' => 'getLastName',
        'ext_id' => 'getExtId',
        'ext_data' => 'getExtData',
        'parent_id' => 'getParentId',
        'enabled' => 'getEnabled',
        'test_mode' => 'getTestMode',
        'hardware_id' => 'getHardwareId'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['entity_type'] = isset($data['entity_type']) ? $data['entity_type'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['ext_id'] = isset($data['ext_id']) ? $data['ext_id'] : null;
        $this->container['ext_data'] = isset($data['ext_data']) ? $data['ext_data'] : null;
        $this->container['parent_id'] = isset($data['parent_id']) ? $data['parent_id'] : null;
        $this->container['enabled'] = isset($data['enabled']) ? $data['enabled'] : null;
        $this->container['test_mode'] = isset($data['test_mode']) ? $data['test_mode'] : null;
        $this->container['hardware_id'] = isset($data['hardware_id']) ? $data['hardware_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets entity_type
     * @return \Swagger\Client\Model\EntityType_[]
     */
    public function getEntityType()
    {
        return $this->container['entity_type'];
    }

    /**
     * Sets entity_type
     * @param \Swagger\Client\Model\EntityType_[] $entity_type
     * @return $this
     */
    public function setEntityType($entity_type)
    {
        $this->container['entity_type'] = $entity_type;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id Unique internal id, used in API to refer entity.
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name User name of entity.
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets last_name
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     * @param string $last_name Last name of entity.
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets ext_id
     * @return string
     */
    public function getExtId()
    {
        return $this->container['ext_id'];
    }

    /**
     * Sets ext_id
     * @param string $ext_id External id, for 3rd party integrations.
     * @return $this
     */
    public function setExtId($ext_id)
    {
        $this->container['ext_id'] = $ext_id;

        return $this;
    }

    /**
     * Gets ext_data
     * @return object
     */
    public function getExtData()
    {
        return $this->container['ext_data'];
    }

    /**
     * Sets ext_data
     * @param object $ext_data Third party entities data.
     * @return $this
     */
    public function setExtData($ext_data)
    {
        $this->container['ext_data'] = $ext_data;

        return $this;
    }

    /**
     * Gets parent_id
     * @return int
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     * @param int $parent_id Parent id, used to identify the entity's parent
     * @return $this
     */
    public function setParentId($parent_id)
    {
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets enabled
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     * @param bool $enabled Enable/disable/delete current unit.   No transactions/login are allowed on disabled units.
     * @return $this
     */
    public function setEnabled($enabled)
    {
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets test_mode
     * @return bool
     */
    public function getTestMode()
    {
        return $this->container['test_mode'];
    }

    /**
     * Sets test_mode
     * @param bool $test_mode Enable/disable test mode on unit.
     * @return $this
     */
    public function setTestMode($test_mode)
    {
        $this->container['test_mode'] = $test_mode;

        return $this;
    }

    /**
     * Gets hardware_id
     * @return string
     */
    public function getHardwareId()
    {
        return $this->container['hardware_id'];
    }

    /**
     * Sets hardware_id
     * @param string $hardware_id Hardware Id
     * @return $this
     */
    public function setHardwareId($hardware_id)
    {
        $this->container['hardware_id'] = $hardware_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


