<?php
/**
 * ExternalAuthResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ExternalAuthResult Class Doc Comment
 *
 * @category    Class
 * @description Hold identification and ownership of logged entites.  | Role        | Description                                                         | |------------ |---------------------------------------------------------------------| | **client**  | Identifies invoiceable root entity, owner of this unit.             | | **unit**    | Identifies account entity, with ownership of credit and tickets.    | | **staff**   | Identifies operator user, of bets placed on account.                | | **manager** | Identifies a backoffice user.                                       | | **api**     | Identifies a 3rd party user, with access to external API.           |
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalAuthResult implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ExternalAuthResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'client' => '\Swagger\Client\Model\AuthResultClient',
        'unit' => '\Swagger\Client\Model\AuthResultClient',
        'staff' => '\Swagger\Client\Model\AuthResultClient',
        'manager' => '\Swagger\Client\Model\AuthResultClient',
        'api' => '\Swagger\Client\Model\AuthResultClient',
        'online_hash' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'client' => 'client',
        'unit' => 'unit',
        'staff' => 'staff',
        'manager' => 'manager',
        'api' => 'api',
        'online_hash' => 'onlineHash'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'client' => 'setClient',
        'unit' => 'setUnit',
        'staff' => 'setStaff',
        'manager' => 'setManager',
        'api' => 'setApi',
        'online_hash' => 'setOnlineHash'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'client' => 'getClient',
        'unit' => 'getUnit',
        'staff' => 'getStaff',
        'manager' => 'getManager',
        'api' => 'getApi',
        'online_hash' => 'getOnlineHash'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['client'] = isset($data['client']) ? $data['client'] : null;
        $this->container['unit'] = isset($data['unit']) ? $data['unit'] : null;
        $this->container['staff'] = isset($data['staff']) ? $data['staff'] : null;
        $this->container['manager'] = isset($data['manager']) ? $data['manager'] : null;
        $this->container['api'] = isset($data['api']) ? $data['api'] : null;
        $this->container['online_hash'] = isset($data['online_hash']) ? $data['online_hash'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets client
     * @return \Swagger\Client\Model\AuthResultClient
     */
    public function getClient()
    {
        return $this->container['client'];
    }

    /**
     * Sets client
     * @param \Swagger\Client\Model\AuthResultClient $client
     * @return $this
     */
    public function setClient($client)
    {
        $this->container['client'] = $client;

        return $this;
    }

    /**
     * Gets unit
     * @return \Swagger\Client\Model\AuthResultClient
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     * @param \Swagger\Client\Model\AuthResultClient $unit
     * @return $this
     */
    public function setUnit($unit)
    {
        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets staff
     * @return \Swagger\Client\Model\AuthResultClient
     */
    public function getStaff()
    {
        return $this->container['staff'];
    }

    /**
     * Sets staff
     * @param \Swagger\Client\Model\AuthResultClient $staff
     * @return $this
     */
    public function setStaff($staff)
    {
        $this->container['staff'] = $staff;

        return $this;
    }

    /**
     * Gets manager
     * @return \Swagger\Client\Model\AuthResultClient
     */
    public function getManager()
    {
        return $this->container['manager'];
    }

    /**
     * Sets manager
     * @param \Swagger\Client\Model\AuthResultClient $manager
     * @return $this
     */
    public function setManager($manager)
    {
        $this->container['manager'] = $manager;

        return $this;
    }

    /**
     * Gets api
     * @return \Swagger\Client\Model\AuthResultClient
     */
    public function getApi()
    {
        return $this->container['api'];
    }

    /**
     * Sets api
     * @param \Swagger\Client\Model\AuthResultClient $api
     * @return $this
     */
    public function setApi($api)
    {
        $this->container['api'] = $api;

        return $this;
    }

    /**
     * Gets online_hash
     * @return string
     */
    public function getOnlineHash()
    {
        return $this->container['online_hash'];
    }

    /**
     * Sets online_hash
     * @param string $online_hash One time session token, to be used for client login with provided credentials.
     * @return $this
     */
    public function setOnlineHash($online_hash)
    {
        $this->container['online_hash'] = $online_hash;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


