<?php
/**
 * FootballTicketEventData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * FootballTicketEventData Class Doc Comment
 *
 * @category    Class
 * @description Representative information for event. Data like league_id or participants  are represented in this entity.  Null for tickets/send operation, fill for other operations. See FootballTicketEventData. Other games null.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FootballTicketEventData implements ArrayAccess
{
    const DISCRIMINATOR = 'classType';

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'FootballTicketEventData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'class_type' => 'string',
        'participants' => '\Swagger\Client\Model\FootballTicketEventDataParticipants[]',
        'league_id' => 'int',
        'match_day' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'class_type' => 'classType',
        'participants' => 'participants',
        'league_id' => 'leagueId',
        'match_day' => 'matchDay'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'class_type' => 'setClassType',
        'participants' => 'setParticipants',
        'league_id' => 'setLeagueId',
        'match_day' => 'setMatchDay'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'class_type' => 'getClassType',
        'participants' => 'getParticipants',
        'league_id' => 'getLeagueId',
        'match_day' => 'getMatchDay'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const CLASS_TYPE_FOOTBALL_TICKET_EVENT_DATA = 'FootballTicketEventData';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getClassTypeAllowableValues()
    {
        return [
            self::CLASS_TYPE_FOOTBALL_TICKET_EVENT_DATA,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['class_type'] = isset($data['class_type']) ? $data['class_type'] : null;
        $this->container['participants'] = isset($data['participants']) ? $data['participants'] : null;
        $this->container['league_id'] = isset($data['league_id']) ? $data['league_id'] : null;
        $this->container['match_day'] = isset($data['match_day']) ? $data['match_day'] : null;

        // Initialize discriminator property with the model name.
        $discriminator = array_search('classType', self::$attributeMap);
        $this->container[$discriminator] = static::$swaggerModelName;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['class_type'] === null) {
            $invalid_properties[] = "'class_type' can't be null";
        }
        $allowed_values = ["FootballTicketEventData"];
        if (!in_array($this->container['class_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'class_type', must be one of 'FootballTicketEventData'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['class_type'] === null) {
            return false;
        }
        $allowed_values = ["FootballTicketEventData"];
        if (!in_array($this->container['class_type'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets class_type
     * @return string
     */
    public function getClassType()
    {
        return $this->container['class_type'];
    }

    /**
     * Sets class_type
     * @param string $class_type
     * @return $this
     */
    public function setClassType($class_type)
    {
        $allowed_values = array('FootballTicketEventData');
        if ((!in_array($class_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'class_type', must be one of 'FootballTicketEventData'");
        }
        $this->container['class_type'] = $class_type;

        return $this;
    }

    /**
     * Gets participants
     * @return \Swagger\Client\Model\FootballTicketEventDataParticipants[]
     */
    public function getParticipants()
    {
        return $this->container['participants'];
    }

    /**
     * Sets participants
     * @param \Swagger\Client\Model\FootballTicketEventDataParticipants[] $participants Participants. Open for extensibility.
     * @return $this
     */
    public function setParticipants($participants)
    {
        $this->container['participants'] = $participants;

        return $this;
    }

    /**
     * Gets league_id
     * @return int
     */
    public function getLeagueId()
    {
        return $this->container['league_id'];
    }

    /**
     * Sets league_id
     * @param int $league_id
     * @return $this
     */
    public function setLeagueId($league_id)
    {
        $this->container['league_id'] = $league_id;

        return $this;
    }

    /**
     * Gets match_day
     * @return int
     */
    public function getMatchDay()
    {
        return $this->container['match_day'];
    }

    /**
     * Sets match_day
     * @param int $match_day
     * @return $this
     */
    public function setMatchDay($match_day)
    {
        $this->container['match_day'] = $match_day;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


