<?php
/**
 * Language
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Language Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Language {
    const WW_WW = 'ww-WW';
    const EN_GB = 'en-GB';
    const NL_NL = 'nl-NL';
    const DE_DE = 'de-DE';
    const TR_TR = 'tr-TR';
    const ES_ES = 'es-ES';
    const PT_PT = 'pt-PT';
    const PL_PL = 'pl-PL';
    const KA_GE = 'ka-GE';
    const HI_IN = 'hi-IN';
    const IT_IT = 'it-IT';
    const AR_AE = 'ar-AE';
    const EL_GR = 'el-GR';
    const ZH_CN = 'zh-CN';
    const RU_KIN = 'ru-KIN';
    const RO_RO = 'ro-RO';
    const RU_RU = 'ru-RU';
    const SK_SK = 'sk-SK';
    const CS_CZ = 'cs-CZ';
    const SQ_AL = 'sq-AL';
    const DA_DK = 'da-DK';
    const FI_FI = 'fi-FI';
    const FR_FR = 'fr-FR';
    const NB_NO = 'nb-NO';
    const SV_SE = 'sv-SE';
    const SL_SI = 'sl-SI';
    const HU_HU = 'hu-HU';
    const SW_KE = 'sw-KE';
    const NE_NE = 'ne-NE';
    const FR_BEL = 'fr-bel';
    const DU_BEL = 'du-bel';
    const ES_DR = 'es-DR';
    const ES_CR = 'es-CR';
    const UK_UKR = 'uk-ukr';
    const JA_JPN = 'ja-jpn';
    const KO_NKO = 'ko-nko';
    const LT_LIT = 'lt-lit';
    const ET_EST = 'et-est';
    const SA_AFR = 'sa-afr';
    const ES_COL = 'es-COL';
    const BU_RUN = 'bu-run';
    const UG_SWA = 'ug-swa';
    const TA_SWA = 'ta-swa';
    const NA_AFR = 'na-afr';
    const BEL_BEL = 'bel-bel';
    const KO_SKO = 'ko-sko';
    const ES_MEX = 'es-mex';
    const KK_KAZ = 'kk-kaz';
    const ES_ARG = 'es-arg';
    const EN_AUS = 'en-aus';
    const VI_VIE = 'vi-vie';
    const LV_LAV = 'lv-lav';
    const TL_TGL = 'tl-tgl';
    const ID_IND = 'id-ind';
    const BEL_RUS = 'bel-rus';
    const PAN_SP = 'pan-sp';
    const CYP_GR = 'cyp-gr';
    const BG_BUL = 'bg-bul';
    const ES_VEN = 'es-ven';
    const RU_MOS = 'ru-mos';
    const KY_RUS = 'ky-rus';
    const RB_RB = 'rb-RB';
    const UK_RU = 'uk-RU';
    const AZ_AZ = 'az-AZ';
    const MK_MKD = 'mk-MKD';
    

    
}

