<?php
/**
 * SingleDisplay
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * SingleDisplay Class Doc Comment
 *
 * @category    Class
 * @description See ContentDisplay and MatrixDisplay
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleDisplay implements ArrayAccess
{
    const DISCRIMINATOR = 'classType';

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'SingleDisplay';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'class_type' => 'string',
        'monitor' => 'int',
        'content' => '\Swagger\Client\Model\SingleDisplayContent'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'class_type' => 'classType',
        'monitor' => 'monitor',
        'content' => 'content'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'class_type' => 'setClassType',
        'monitor' => 'setMonitor',
        'content' => 'setContent'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'class_type' => 'getClassType',
        'monitor' => 'getMonitor',
        'content' => 'getContent'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const CLASS_TYPE_SINGLE_DISPLAY = 'SingleDisplay';
    const CLASS_TYPE_MATRIX_DISPLAY = 'MatrixDisplay';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getClassTypeAllowableValues()
    {
        return [
            self::CLASS_TYPE_SINGLE_DISPLAY,
            self::CLASS_TYPE_MATRIX_DISPLAY,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['class_type'] = isset($data['class_type']) ? $data['class_type'] : null;
        $this->container['monitor'] = isset($data['monitor']) ? $data['monitor'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;

        // Initialize discriminator property with the model name.
        $discriminator = array_search('classType', self::$attributeMap);
        $this->container[$discriminator] = static::$swaggerModelName;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['class_type'] === null) {
            $invalid_properties[] = "'class_type' can't be null";
        }
        $allowed_values = ["SingleDisplay", "MatrixDisplay"];
        if (!in_array($this->container['class_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'class_type', must be one of 'SingleDisplay', 'MatrixDisplay'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['class_type'] === null) {
            return false;
        }
        $allowed_values = ["SingleDisplay", "MatrixDisplay"];
        if (!in_array($this->container['class_type'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets class_type
     * @return string
     */
    public function getClassType()
    {
        return $this->container['class_type'];
    }

    /**
     * Sets class_type
     * @param string $class_type
     * @return $this
     */
    public function setClassType($class_type)
    {
        $allowed_values = array('SingleDisplay', 'MatrixDisplay');
        if ((!in_array($class_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'class_type', must be one of 'SingleDisplay', 'MatrixDisplay'");
        }
        $this->container['class_type'] = $class_type;

        return $this;
    }

    /**
     * Gets monitor
     * @return int
     */
    public function getMonitor()
    {
        return $this->container['monitor'];
    }

    /**
     * Sets monitor
     * @param int $monitor
     * @return $this
     */
    public function setMonitor($monitor)
    {
        $this->container['monitor'] = $monitor;

        return $this;
    }

    /**
     * Gets content
     * @return \Swagger\Client\Model\SingleDisplayContent
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     * @param \Swagger\Client\Model\SingleDisplayContent $content
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


