name: Bump version and push tags

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bump version
        run: |
          CURRENT_VERSION=$(grep version pyproject.toml | head -n 1 | cut -d '"' -f2)
          echo "Versi칩n actual: $CURRENT_VERSION"
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          echo "Nueva versi칩n: $NEW_VERSION"
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
          git config user.name "KarlaVirtual"
          git config user.email "karla.ramirez@virtualsoft.tech"
          git commit -am "Bump versi칩n autom치tica: v$NEW_VERSION"
          git tag "v$NEW_VERSION"

      - name: Push cambios y tags
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KarlaVirtual/back_test.git
          git push origin main --follow-tags
