name: Versionado con TAG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.email "karla@example.com"
          git config --global user.name "Karla Ramirez"

      - name: Leer versión del archivo VERSION.txt
        id: version
        run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_OUTPUT

      - name: Crear tag con la versión
        run: |
          git tag ${{ steps.version.outputs.VERSION }}

      - name: Push tag a GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GH_TOKEN }}
