name: Versionado y Push

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  versionar-y-pushear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.email "karla.ramirez@virtualsoft.tech"
          git config --global user.name "KarlaVirtual"

      - name: Incrementar versión en VERSION.txt y hacer commit con tag
        run: |
          # Leer versión actual (sin 'v')
          VERSION_ANTERIOR=$(cat VERSION.txt | tr -d 'v')
          echo "Versión anterior: $VERSION_ANTERIOR"

          # Separar en partes
          IFS='.' read -r major minor patch <<< "$VERSION_ANTERIOR"

          # Incrementar patch
          NUEVA_VERSION="$major.$minor.$((patch+1))"
          echo "Nueva versión: v$NUEVA_VERSION"

          # Sobrescribir archivo
          echo "v$NUEVA_VERSION" > VERSION.txt

          # Hacer commit y tag
          git add VERSION.txt
          git commit -m "chore: bump version to v$NUEVA_VERSION"
          git tag "v$NUEVA_VERSION"

          # Establecer remote con token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/KarlaVirtual/back_test.git

          # Push con tag
          git push origin main
          git push origin "v$NUEVA_VERSION"

      - name: Simular creación de imagen
        run: |
          VERSION=$(cat VERSION.txt)
          IMAGE_NAME="back_test-$VERSION"
      
          echo "Simulando creación de imagen: $IMAGE_NAME"
          echo "oci compute image create --instance-id OCID --display-name $IMAGE_NAME --compartment-id OCID"
