name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump version in VERSION.txt
        run: |
          VERSION=$(cat VERSION.txt)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo "$NEW_VERSION" > VERSION.txt

      - name: Commit version change
        run: |
          git add VERSION.txt
          git commit -m "Bump versión automática: v$(cat VERSION.txt)"

      - name: Push tag to GitHub
        run: |
          git config user.name "KarlaVirtual"
          git config user.email "karla.ramirez@virtualsoft.tech"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KarlaVirtual/back_test.git
          git push origin --tags
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
