name: Versionado y generación de imagen en Oracle

on:
  push:
    branches:
      - main

jobs:
  versionar-y-generar-imagen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_PUSH_TOKEN }}

      - name: Configurar Git
        run: |
          git config user.name "KarlaVirtual"
          git config user.email "karla.ramirez@virtualsoft.tech"

      - name: Incrementar versión en VERSION.txt y hacer commit
        run: |
          # Leer versión actual (sin 'v')
          VERSION_ANTERIOR=$(cat VERSION.txt | tr -d 'v')
          echo "Versión anterior: $VERSION_ANTERIOR"

          # Separar en partes
          IFS='.' read -r major minor patch <<< "$VERSION_ANTERIOR"

          # Incrementar patch
          NUEVA_VERSION="$major.$minor.$((patch+1))"
          echo "Nueva versión: v$NUEVA_VERSION"

          # Sobrescribir archivo
          echo "v$NUEVA_VERSION" > VERSION.txt

      - name: Hacer commit del archivo VERSION.txt
        run: |
          git add VERSION.txt
          git commit -m "chore: actualizar versión automática [skip ci]" || echo "Sin cambios"

      - name: Configurar git y hacer push con token clásico
        env:
          GH_PAT: ${{ secrets.PAT_PUSH_TOKEN }}
        run: |
          git config --global user.email "karla@example.com"
          git config --global user.name "Karla Ramirez"
          git remote set-url origin https://KarlaVirtual:${GH_PAT}@github.com/KarlaVirtual/back_test.git
          git push origin main
      
        #Push del tag
      - name: Crear y hacer push del tag
        env:
          TOKEN: ${{ secrets.PAT_PUSH_TOKEN }}
        run: |
          VERSION=$(cat VERSION.txt | tr -d 'v')
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG

      - name: Disparar construcción de imagen en Oracle (simulado)
        run: |
          echo "Llamar al endpoint de Oracle para construir imagen..."
          # curl -X POST "https://oracle-api/imagen/build" -H "Authorization: Bearer ${{ secrets.ORACLE_API_TOKEN }}"
