name: Versionado y Push

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  versionar-y-pushear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.email "karla.ramirez@virtualsoft.tech"
          git config --global user.name "KarlaVirtual"

      - name: Bump versión y commit
        id: version
        run: |
          git fetch origin main
          git checkout origin/main -- VERSION.txt

          CURRENT_VERSION=$(cat VERSION.txt | tr -d 'v')
          echo "Versión actual: $CURRENT_VERSION"

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          echo "Nueva versión: v$NEW_VERSION"

          echo "v$NEW_VERSION" > VERSION.txt
          echo "VERSION=v$NEW_VERSION" >> $GITHUB_OUTPUT

          git add VERSION.txt
          git commit -m "Bump versión automática: v$NEW_VERSION"
          git tag "v$NEW_VERSION"

      - name: Establecer nuevo remoto con GITHUB_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/KarlaVirtual/back_test.git

      - name: Push commit y tag
        run: |
          git push origin main
          git push origin "v${{ steps.version.outputs.VERSION }}"
