name: Versionado y Push

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  versionar-y-pushear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.email "karla.ramirez@virtualsoft.tech"
          git config --global user.name "KarlaVirtual"

      - name: Calcular nueva versión
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          echo "$VERSION" > VERSION.txt
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit y Tag del versionado
        run: |
          git add VERSION.txt
          git commit -m "chore: version ${VERSION}"
          git tag ${VERSION}
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Establecer nuevo remoto con GITHUB_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/KarlaVirtual/back_test.git

      - name: Push con tags
        run: |
          git push origin main --follow-tags
