name: Versionado con TAG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.email "karla@example.com"
          git config --global user.name "Karla Ramirez"

      - name: Leer versión del archivo VERSION.txt
        id: version
        run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_OUTPUT

      - name: Establecer remote autenticado con token
        run: |
          git remote set-url origin https://karlaVirtual:${{ secrets.GH_TOKEN }}@github.com/KarlaVirtual/back_test.git

      - name: Crear y pushear tag con versión
        run: |
          git tag ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.VERSION }}
