<?php
/**
 * AuthResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuthResultTest Class Doc Comment
 *
 * @category    Class */
// * @description Hold identification and ownership of logged entites.  | Role        | Description                                                         | |------------ |---------------------------------------------------------------------| | **client**  | Identifies invoiceable root entity, owner of this unit.             | | **unit**    | Identifies account entity, with ownership of credit and tickets.    | | **staff**   | Identifies operator user, of bets placed on account.                | | **manager** | Identifies a backoffice user.                                       | | **api**     | Identifies a 3rd party user, with access to external API.           |
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AuthResult"
     */
    public function testAuthResult()
    {

    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {

    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {

    }

    /**
     * Test attribute "staff"
     */
    public function testPropertyStaff()
    {

    }

    /**
     * Test attribute "manager"
     */
    public function testPropertyManager()
    {

    }

    /**
     * Test attribute "api"
     */
    public function testPropertyApi()
    {

    }

    /**
     * Test attribute "online_hash"
     */
    public function testPropertyOnlineHash()
    {

    }

}
