<?php
/**
 * InlineResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200Test Class Doc Comment
 *
 * @category    Class */
// * @description Information about credit transaction operations.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponse200"
     */
    public function testInlineResponse200()
    {

    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {

    }

    /**
     * Test attribute "ext_transaction_id"
     */
    public function testPropertyExtTransactionId()
    {

    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "ext_id"
     */
    public function testPropertyExtId()
    {

    }

    /**
     * Test attribute "ticket_id"
     */
    public function testPropertyTicketId()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "previous_credit"
     */
    public function testPropertyPreviousCredit()
    {

    }

    /**
     * Test attribute "new_credit"
     */
    public function testPropertyNewCredit()
    {

    }

    /**
     * Test attribute "change_credit"
     */
    public function testPropertyChangeCredit()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

}
