<?php
/**
 * JackpotStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JackpotStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description Object to define the Jackpot information. The information is the JackpotId, type, name of jackpot, amount, currency and date of last operation.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JackpotStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "JackpotStatus"
     */
    public function testJackpotStatus()
    {

    }

    /**
     * Test attribute "jackpot_id"
     */
    public function testPropertyJackpotId()
    {

    }

    /**
     * Test attribute "jackpot_type"
     */
    public function testPropertyJackpotType()
    {

    }

    /**
     * Test attribute "jackpot_name"
     */
    public function testPropertyJackpotName()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "last_jackpot"
     */
    public function testPropertyLastJackpot()
    {

    }

}
