<?php
/**
 * PlaylistTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PlaylistTest Class Doc Comment
 *
 * @category    Class */
// * @description Information about a game type playlist events.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlaylistTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Playlist"
     */
    public function testPlaylist()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "game_type"
     */
    public function testPropertyGameType()
    {

    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {

    }

    /**
     * Test attribute "filter"
     */
    public function testPropertyFilter()
    {

    }

    /**
     * Test attribute "capabilities"
     */
    public function testPropertyCapabilities()
    {

    }

    /**
     * Test attribute "market_option_size"
     */
    public function testPropertyMarketOptionSize()
    {

    }

    /**
     * Test attribute "market_templates"
     */
    public function testPropertyMarketTemplates()
    {

    }

    /**
     * Test attribute "participant_templates"
     */
    public function testPropertyParticipantTemplates()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

}
