<?php
/**
 * RaceParticipantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RaceParticipantTest Class Doc Comment
 *
 * @category    Class */
// * @description See FootballParticipant and RaceParticipant
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RaceParticipantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RaceParticipant"
     */
    public function testRaceParticipant()
    {

    }

    /**
     * Test attribute "class_type"
     */
    public function testPropertyClassType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "prob"
     */
    public function testPropertyProb()
    {

    }

    /**
     * Test attribute "forecast"
     */
    public function testPropertyForecast()
    {

    }

    /**
     * Test attribute "sex"
     */
    public function testPropertySex()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "speed"
     */
    public function testPropertySpeed()
    {

    }

    /**
     * Test attribute "stamina"
     */
    public function testPropertyStamina()
    {

    }

    /**
     * Test attribute "place"
     */
    public function testPropertyPlace()
    {

    }

    /**
     * Test attribute "wins"
     */
    public function testPropertyWins()
    {

    }

    /**
     * Test attribute "time_off"
     */
    public function testPropertyTimeOff()
    {

    }

    /**
     * Test attribute "handicap"
     */
    public function testPropertyHandicap()
    {

    }

    /**
     * Test attribute "handicap_prev"
     */
    public function testPropertyHandicapPrev()
    {

    }

    /**
     * Test attribute "jockey"
     */
    public function testPropertyJockey()
    {

    }

    /**
     * Test attribute "jockey_forecast"
     */
    public function testPropertyJockeyForecast()
    {

    }

    /**
     * Test attribute "pace"
     */
    public function testPropertyPace()
    {

    }

    /**
     * Test attribute "art"
     */
    public function testPropertyArt()
    {

    }

    /**
     * Test attribute "form"
     */
    public function testPropertyForm()
    {

    }

    /**
     * Test attribute "median"
     */
    public function testPropertyMedian()
    {

    }

    /**
     * Test attribute "standard_deviation"
     */
    public function testPropertyStandardDeviation()
    {

    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {

    }

    /**
     * Test attribute "risk"
     */
    public function testPropertyRisk()
    {

    }

    /**
     * Test attribute "ability"
     */
    public function testPropertyAbility()
    {

    }

    /**
     * Test attribute "star"
     */
    public function testPropertyStar()
    {

    }

    /**
     * Test attribute "track_condition"
     */
    public function testPropertyTrackCondition()
    {

    }

}
