<?php
/**
 * SellTicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SellTicketTest Class Doc Comment
 *
 * @category    Class */
// * @description Entity for send ticket data to server
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SellTicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SellTicket"
     */
    public function testSellTicket()
    {

    }

    /**
     * Test attribute "time_send"
     */
    public function testPropertyTimeSend()
    {

    }

    /**
     * Test attribute "sell_staff"
     */
    public function testPropertySellStaff()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "odd_settings_id"
     */
    public function testPropertyOddSettingsId()
    {

    }

    /**
     * Test attribute "game_type"
     */
    public function testPropertyGameType()
    {

    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {

    }

}
