<?php
/**
 * ServerTicketWinningDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerTicketWinningDataTest Class Doc Comment
 *
 * @category    Class */
// * @description This information is only availabe when ticket is OPEN. Is necesary in many situation, for example, to print recover not-printed tickets. Return null when not available. Total amount that system will pay to ticket owner for this system bet. Rule to pay:  - maxWinning + bonus &lt; maxPayout ? maxWinning + bonus : maxPayout
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerTicketWinningDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ServerTicketWinningData"
     */
    public function testServerTicketWinningData()
    {

    }

    /**
     * Test attribute "limit_max_payout"
     */
    public function testPropertyLimitMaxPayout()
    {

    }

    /**
     * Test attribute "min_winning"
     */
    public function testPropertyMinWinning()
    {

    }

    /**
     * Test attribute "max_winning"
     */
    public function testPropertyMaxWinning()
    {

    }

    /**
     * Test attribute "min_bonus"
     */
    public function testPropertyMinBonus()
    {

    }

    /**
     * Test attribute "max_bonus"
     */
    public function testPropertyMaxBonus()
    {

    }

}
