<?php
/**
 * ServerTicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerTicketTest Class Doc Comment
 *
 * @category    Class */
// * @description Entity for recive ticket data from server
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerTicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ServerTicket"
     */
    public function testServerTicket()
    {

    }

    /**
     * Test attribute "ticket_id"
     */
    public function testPropertyTicketId()
    {

    }

    /**
     * Test attribute "ext_id"
     */
    public function testPropertyExtId()
    {

    }

    /**
     * Test attribute "ext_data"
     */
    public function testPropertyExtData()
    {

    }

    /**
     * Test attribute "server_hash"
     */
    public function testPropertyServerHash()
    {

    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {

    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {

    }

    /**
     * Test attribute "pay_staff"
     */
    public function testPropertyPayStaff()
    {

    }

    /**
     * Test attribute "sell_staff"
     */
    public function testPropertySellStaff()
    {

    }

    /**
     * Test attribute "time_send"
     */
    public function testPropertyTimeSend()
    {

    }

    /**
     * Test attribute "time_register"
     */
    public function testPropertyTimeRegister()
    {

    }

    /**
     * Test attribute "time_resolved"
     */
    public function testPropertyTimeResolved()
    {

    }

    /**
     * Test attribute "time_cancelled"
     */
    public function testPropertyTimeCancelled()
    {

    }

    /**
     * Test attribute "time_paid"
     */
    public function testPropertyTimePaid()
    {

    }

    /**
     * Test attribute "time_closed_market"
     */
    public function testPropertyTimeClosedMarket()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "stake"
     */
    public function testPropertyStake()
    {

    }

    /**
     * Test attribute "stake_taxes"
     */
    public function testPropertyStakeTaxes()
    {

    }

    /**
     * Test attribute "won_data"
     */
    public function testPropertyWonData()
    {

    }

    /**
     * Test attribute "winning_data"
     */
    public function testPropertyWinningData()
    {

    }

    /**
     * Test attribute "odd_settings_id"
     */
    public function testPropertyOddSettingsId()
    {

    }

    /**
     * Test attribute "game_type"
     */
    public function testPropertyGameType()
    {

    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {

    }

}
