<?php
/**
 * Stat1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Stat1Test Class Doc Comment
 *
 * @category    Class */
// * @description Earning consolidate information per ticket.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Stat1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Stat1"
     */
    public function testStat1()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "parent_client_id"
     */
    public function testPropertyParentClientId()
    {

    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

    /**
     * Test attribute "user_played"
     */
    public function testPropertyUserPlayed()
    {

    }

    /**
     * Test attribute "currency_iso"
     */
    public function testPropertyCurrencyIso()
    {

    }

    /**
     * Test attribute "stake"
     */
    public function testPropertyStake()
    {

    }

    /**
     * Test attribute "won"
     */
    public function testPropertyWon()
    {

    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {

    }

    /**
     * Test attribute "taxes_paid_out"
     */
    public function testPropertyTaxesPaidOut()
    {

    }

    /**
     * Test attribute "jackpot_contribution"
     */
    public function testPropertyJackpotContribution()
    {

    }

    /**
     * Test attribute "jackpot"
     */
    public function testPropertyJackpot()
    {

    }

    /**
     * Test attribute "megajackpot"
     */
    public function testPropertyMegajackpot()
    {

    }

    /**
     * Test attribute "stake_cancelled"
     */
    public function testPropertyStakeCancelled()
    {

    }

    /**
     * Test attribute "paid"
     */
    public function testPropertyPaid()
    {

    }

    /**
     * Test attribute "lapsed"
     */
    public function testPropertyLapsed()
    {

    }

    /**
     * Test attribute "played_tickets"
     */
    public function testPropertyPlayedTickets()
    {

    }

    /**
     * Test attribute "cancelledtickets"
     */
    public function testPropertyCancelledtickets()
    {

    }

    /**
     * Test attribute "won_tickets"
     */
    public function testPropertyWonTickets()
    {

    }

    /**
     * Test attribute "playlist"
     */
    public function testPropertyPlaylist()
    {

    }

    /**
     * Test attribute "gametype"
     */
    public function testPropertyGametype()
    {

    }

    /**
     * Test attribute "jackpot_paid"
     */
    public function testPropertyJackpotPaid()
    {

    }

    /**
     * Test attribute "megajackpot_paid"
     */
    public function testPropertyMegajackpotPaid()
    {

    }

}
