<?php
/**
 * TicketEventsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoldenRace External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TicketEventsTest Class Doc Comment
 *
 * @category    Class */
// * @description Information about ticket events.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketEventsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TicketEvents"
     */
    public function testTicketEvents()
    {

    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {

    }

    /**
     * Test attribute "ext_id"
     */
    public function testPropertyExtId()
    {

    }

    /**
     * Test attribute "ext_data"
     */
    public function testPropertyExtData()
    {

    }

    /**
     * Test attribute "playlist_id"
     */
    public function testPropertyPlaylistId()
    {

    }

    /**
     * Test attribute "playlist_description"
     */
    public function testPropertyPlaylistDescription()
    {

    }

    /**
     * Test attribute "game_type"
     */
    public function testPropertyGameType()
    {

    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {

    }

    /**
     * Test attribute "final_outcome"
     */
    public function testPropertyFinalOutcome()
    {

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {

    }

    /**
     * Test attribute "is_banker"
     */
    public function testPropertyIsBanker()
    {

    }

    /**
     * Test attribute "bets"
     */
    public function testPropertyBets()
    {

    }

}
